# Generated by Django 2.2 on 2020-01-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('plastic_type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
